### PR TITLE
Update associate editors

### PR DESCRIPTION
**Pull request by floe**
add Houda, re-sort

### CODE REVIEW

**Review by mjskay — APPROVED** [review]

**Comment by floe** [comment]
Doesn't seem to get pushed to the website? Anything I still would need to do?

**Comment by mjskay** [comment]
I dunno, looks like a spurious failure of the pages deploy action (see the "Actions" tab). I am re-running the quarto publish job to see if that fixes it.

**Comment by mjskay** [comment]
Got an internal error: https://github.com/journalovi/journalovi.github.io/actions/runs/4941533378

Looks like maybe there are problems with Github actions at the moment: https://twitter.com/githubstatus/status/1656406770749784064

**Comment by mjskay** [comment]
Github pages is back up so I re-run the pages deployment job. Should be up now.

**Pull request merged**
