### PR TITLE
Add link to structured abstract explanation + visual example

### PR DESCRIPTION
**Pull request by chatchavan**

### CODE REVIEW

**Comment by chatchavan** [comment]
@floe, @lonnibesancon: This is a minor edit. Once you are OK with it, please merge this PR.

**Comment by mjskay** [comment]
I don't think the elements of that table were intended to be alternatives to each other, but the new layout kind of implies they are (and I can see how the old layout did as well).

Perhaps we should just make this a list instead of a table?

**Comment by chatchavan** [comment]
I revised them into two lists

**Comment by mjskay** [comment]
I was pretty sure we had written a more complete version of this somewhere and realized it was in the quarto template. See the abstract here: https://www.journalovi.org/jovi-template-quarto/

Maybe we just copy that text?

**Comment by chatchavan** [comment]
Oh gosh. Yes. copied.

**Comment by chatchavan** [comment]
Do we only "recommend" or "require" structured abstract? 

The phrasing in the Abstract section previously said:

> JOVI __encourages__ you to use structured abstracts

But this Abstract subsection is under the "What do I need to make a submission?" section.

**Comment by mjskay** [comment]
I believe we had decided on "recommend" but I might be misremembering.

**Comment by chatchavan** [comment]
The current wording is "encouraged". So your recollection is consistent with the wording on the website.

I adjusted the issue template to mirror this conclusion: https://github.com/journalovi/jovi-workflows/commit/223b0278191ea704e76e2f3f7ca61730f8255de6. 

(I accidentally edited it directly instead of making a pull request. Sorry!)

**Comment by mjskay** [comment]
No worries, thanks!

**Pull request merged**
