### PR TITLE
clarify AEs may see authors during conflict resolution

### PR DESCRIPTION
**Pull request by mjskay**

### CODE REVIEW

**Comment by chatchavan** [comment]
@mjskay I'm unsure why we need this sentence. It seems to be redundant with the sentence immediately preceding (quoted in bold below):

> **Editors will always know who the authors and the reviewers are.** Potential editors may see who the authors are when resolving conflicts.

The only explanation seems to be the difference between "Editors" and "Potential editors". It is not clear to me why these people won't be the same people.

**Comment by mjskay** [comment]
Yes, this came from discussion at the meeting today --- the point is to clarify that potential editors might see who the authors are before the paper is assigned / conflicts are resolved, which is a bit different from some venues (e.g. VIS) where AC conflicts are resolved before the editor sees the paper.

I'm also not sure we need to make this distinction as it is quite subtle, I think either @floe or @lonnibesancon brought it up if they want to chime in...

**Comment by floe** [comment]
Yes, it's rather subtle right now, but I think once we get a higher volume of submissions, the only way to handle this is to post the frontmatter of each submission in the #jovi_editors channel or on the mailing list, and let people self-select what they want to be AE for. And that means that all potential editors will get to see authors and abstract of all submissions.

**Review by floe — APPROVED** [review]

**Comment by chatchavan** [comment]
I think I understand the scenario now. I'd propose the following wording:

> Potential editors may see who the authors are during editor-recruitment.

**Comment by mjskay** [comment]
Oh yeah I like that! Updated.

**Pull request merged**
